# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_jeu.ui'
#
# Created: Mon Jan  9 01:17:59 2012
#      by: pyside-uic 0.2.11 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 485)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(10, 10, 10, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.phraseLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phraseLabel.sizePolicy().hasHeightForWidth())
        self.phraseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phraseLabel.setFont(font)
        self.phraseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phraseLabel.setWordWrap(True)
        self.phraseLabel.setObjectName("phraseLabel")
        self.verticalLayout_4.addWidget(self.phraseLabel)
        self.labelPartie = QtGui.QLabel(self.centralwidget)
        self.labelPartie.setObjectName("labelPartie")
        self.verticalLayout_4.addWidget(self.labelPartie)
        self.labelMessage = QtGui.QLabel(self.centralwidget)
        self.labelMessage.setText("")
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout_4.addWidget(self.labelMessage)
        self.textEditEntry = QtGui.QLineEdit(self.centralwidget)
        self.textEditEntry.setObjectName("textEditEntry")
        self.verticalLayout_4.addWidget(self.textEditEntry)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.errorsLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.errorsLabel.setFont(font)
        self.errorsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.errorsLabel.setObjectName("errorsLabel")
        self.horizontalLayout_4.addWidget(self.errorsLabel)
        self.errorsStrLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.errorsStrLabel.setFont(font)
        self.errorsStrLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.errorsStrLabel.setObjectName("errorsStrLabel")
        self.horizontalLayout_4.addWidget(self.errorsStrLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.indicesNbLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.indicesNbLabel.setFont(font)
        self.indicesNbLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.indicesNbLabel.setObjectName("indicesNbLabel")
        self.horizontalLayout_5.addWidget(self.indicesNbLabel)
        self.indicesNbStrLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.indicesNbStrLabel.setFont(font)
        self.indicesNbStrLabel.setObjectName("indicesNbStrLabel")
        self.horizontalLayout_5.addWidget(self.indicesNbStrLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.passerButton = QtGui.QPushButton(self.centralwidget)
        self.passerButton.setObjectName("passerButton")
        self.horizontalLayout.addWidget(self.passerButton)
        self.indiceButton = QtGui.QPushButton(self.centralwidget)
        self.indiceButton.setObjectName("indiceButton")
        self.horizontalLayout.addWidget(self.indiceButton)
        self.validerButton = QtGui.QPushButton(self.centralwidget)
        self.validerButton.setObjectName("validerButton")
        self.horizontalLayout.addWidget(self.validerButton)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.scoreLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreLabel.setObjectName("scoreLabel")
        self.verticalLayout_3.addWidget(self.scoreLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pythonnd Jeu", None, QtGui.QApplication.UnicodeUTF8))
        self.phraseLabel.setText(QtGui.QApplication.translate("MainWindow", "phrase", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPartie.setText(QtGui.QApplication.translate("MainWindow", "Devinez !", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Indices", None, QtGui.QApplication.UnicodeUTF8))
        self.errorsLabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.errorsStrLabel.setText(QtGui.QApplication.translate("MainWindow", "Erreurs", None, QtGui.QApplication.UnicodeUTF8))
        self.indicesNbLabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.indicesNbStrLabel.setText(QtGui.QApplication.translate("MainWindow", "Indice(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.passerButton.setText(QtGui.QApplication.translate("MainWindow", "Passer", None, QtGui.QApplication.UnicodeUTF8))
        self.indiceButton.setText(QtGui.QApplication.translate("MainWindow", "Indice", None, QtGui.QApplication.UnicodeUTF8))
        self.validerButton.setText(QtGui.QApplication.translate("MainWindow", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.scoreLabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))

