# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pythonndITAL.ui'
#
# Created: Sun Jan  8 17:29:57 2012
#      by: pyside-uic 0.2.11 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PythonndITAL(object):
    def setupUi(self, PythonndITAL):
        PythonndITAL.setObjectName("PythonndITAL")
        PythonndITAL.resize(500, 300)
        PythonndITAL.setMinimumSize(QtCore.QSize(500, 300))
        PythonndITAL.setLayoutDirection(QtCore.Qt.LeftToRight)
        PythonndITAL.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(PythonndITAL)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lcdNumber)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lcdNumber_2)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lcdNumber_3)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalSlider = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setPageStep(3)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.horizontalSlider)
        self.verticalLayout.addLayout(self.formLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.startGameButton = QtGui.QPushButton(self.centralwidget)
        self.startGameButton.setObjectName("startGameButton")
        self.verticalLayout.addWidget(self.startGameButton)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        PythonndITAL.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PythonndITAL)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        self.menuPartie = QtGui.QMenu(self.menubar)
        self.menuPartie.setObjectName("menuPartie")
        self.menuApprentisage = QtGui.QMenu(self.menubar)
        self.menuApprentisage.setObjectName("menuApprentisage")
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        self.menuDictionnaire = QtGui.QMenu(self.menubar)
        self.menuDictionnaire.setObjectName("menuDictionnaire")
        PythonndITAL.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PythonndITAL)
        self.statusbar.setObjectName("statusbar")
        PythonndITAL.setStatusBar(self.statusbar)
        self.actionPlayerOpen = QtGui.QAction(PythonndITAL)
        self.actionPlayerOpen.setObjectName("actionPlayerOpen")
        self.actionPlayerSave = QtGui.QAction(PythonndITAL)
        self.actionPlayerSave.setObjectName("actionPlayerSave")
        self.actionBiCorpusMonolingue = QtGui.QAction(PythonndITAL)
        self.actionBiCorpusMonolingue.setObjectName("actionBiCorpusMonolingue")
        self.actionServicesTraduction = QtGui.QAction(PythonndITAL)
        self.actionServicesTraduction.setObjectName("actionServicesTraduction")
        self.actionAbout = QtGui.QAction(PythonndITAL)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDicoOpen = QtGui.QAction(PythonndITAL)
        self.actionDicoOpen.setObjectName("actionDicoOpen")
        self.actionDicoSave = QtGui.QAction(PythonndITAL)
        self.actionDicoSave.setObjectName("actionDicoSave")
        self.actionDicoNew = QtGui.QAction(PythonndITAL)
        self.actionDicoNew.setObjectName("actionDicoNew")
        self.actionPlayerNew = QtGui.QAction(PythonndITAL)
        self.actionPlayerNew.setObjectName("actionPlayerNew")
        self.actionDicoShow = QtGui.QAction(PythonndITAL)
        self.actionDicoShow.setObjectName("actionDicoShow")
        self.menuPartie.addAction(self.actionPlayerNew)
        self.menuPartie.addAction(self.actionPlayerOpen)
        self.menuPartie.addAction(self.actionPlayerSave)
        self.menuApprentisage.addAction(self.actionBiCorpusMonolingue)
        self.menuApprentisage.addAction(self.actionServicesTraduction)
        self.menuAide.addAction(self.actionAbout)
        self.menuDictionnaire.addAction(self.actionDicoNew)
        self.menuDictionnaire.addAction(self.actionDicoOpen)
        self.menuDictionnaire.addAction(self.actionDicoSave)
        self.menuDictionnaire.addSeparator()
        self.menuDictionnaire.addAction(self.actionDicoShow)
        self.menubar.addAction(self.menuPartie.menuAction())
        self.menubar.addAction(self.menuDictionnaire.menuAction())
        self.menubar.addAction(self.menuApprentisage.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(PythonndITAL)
        QtCore.QMetaObject.connectSlotsByName(PythonndITAL)

    def retranslateUi(self, PythonndITAL):
        PythonndITAL.setWindowTitle(QtGui.QApplication.translate("PythonndITAL", "Pythonn\'d ITAL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PythonndITAL", "Bienvenue !", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PythonndITAL", "Nombre de parties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PythonndITAL", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PythonndITAL", "Meilleure partie", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PythonndITAL", "Jouer :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PythonndITAL", "Nombre de devinettes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PythonndITAL", "Difficulté", None, QtGui.QApplication.UnicodeUTF8))
        self.startGameButton.setText(QtGui.QApplication.translate("PythonndITAL", "C\'est parti !", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPartie.setTitle(QtGui.QApplication.translate("PythonndITAL", "Partie", None, QtGui.QApplication.UnicodeUTF8))
        self.menuApprentisage.setTitle(QtGui.QApplication.translate("PythonndITAL", "Apprentisage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAide.setTitle(QtGui.QApplication.translate("PythonndITAL", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDictionnaire.setTitle(QtGui.QApplication.translate("PythonndITAL", "Dictionnaire", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayerOpen.setText(QtGui.QApplication.translate("PythonndITAL", "Ouvrir...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayerSave.setText(QtGui.QApplication.translate("PythonndITAL", "Sauvegarder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBiCorpusMonolingue.setText(QtGui.QApplication.translate("PythonndITAL", "Bi-Corpus Monolingue", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServicesTraduction.setText(QtGui.QApplication.translate("PythonndITAL", "Services de traduction", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("PythonndITAL", "À propos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDicoOpen.setText(QtGui.QApplication.translate("PythonndITAL", "Ouvrir...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDicoSave.setText(QtGui.QApplication.translate("PythonndITAL", "Sauvegarder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDicoNew.setText(QtGui.QApplication.translate("PythonndITAL", "Nouveau", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayerNew.setText(QtGui.QApplication.translate("PythonndITAL", "Nouvelle Partie", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDicoShow.setText(QtGui.QApplication.translate("PythonndITAL", "Visualiser", None, QtGui.QApplication.UnicodeUTF8))

